[package]
name = "pointercrate-integrate"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.7", default-features = false, features = [ "runtime-tokio-native-tls", "macros", "postgres", "chrono" ] }
bincode = "1.3.1"
reqwest = "0.11.*"
futures = "0.3.8"
log = "0.4.11"
chrono = "0.4.19"
tokio = {version = "1.20.4", features = ["rt"]}
pointercrate-demonlist = { path = "../pointercrate-demonlist" }
pointercrate-core = { path = "../pointercrate-core" }
governor = "0.6.3"
nonzero_ext = "0.3.0"

[dependencies.dash-rs]
git = "https://github.com/stadust/dash-rs"
rev = "8cdbb85625b7575b8775e6e28ce6850504bc7397"
