[package]
name = "pointercrate-demonlist-api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
pointercrate-demonlist = {path = "../pointercrate-demonlist"}
pointercrate-core = {path = "../pointercrate-core"}
pointercrate-core-api = {path = "../pointercrate-core-api"}
pointercrate-user-api = {path = "../pointercrate-user-api"}
serde_json = "1.0.60"
